--------------------------------------------------------
--  File created - Tuesday-April-28-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SERVICE_CH
--------------------------------------------------------

  CREATE TABLE "LALOU"."SERVICE_CH" 
   (	"ID_SER_CH" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"ID_CH" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into LALOU.SERVICE_CH
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SERVICE_CH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LALOU"."SERVICE_CH_PK" ON "LALOU"."SERVICE_CH" ("ID_SER_CH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SERVICE_CH
--------------------------------------------------------

  ALTER TABLE "LALOU"."SERVICE_CH" ADD CONSTRAINT "SERVICE_CH_PK" PRIMARY KEY ("ID_SER_CH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LALOU"."SERVICE_CH" MODIFY ("ID_SER_CH" NOT NULL ENABLE);
